# Generated by Django 3.1.5 on 2021-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210310_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='number',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
