# Generated by Django 3.1.5 on 2021-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210310_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='call',
        ),
        migrations.AddField(
            model_name='lead',
            name='calling',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
