# Generated by Django 3.1.5 on 2021-03-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210310_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='calling',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='number',
        ),
    ]
