# Generated by Django 3.1.5 on 2021-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210310_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='calling',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
