# Generated by Django 3.1.5 on 2021-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210310_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='calling',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
