# Generated by Django 3.1.5 on 2021-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210311_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='enddate',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intern',
            name='intern_cource',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='startdate',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainee',
            name='enddate',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainee',
            name='startdate',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainee_cource',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='date',
            field=models.CharField(blank=True, default='13-03-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='internattendance',
            name='date',
            field=models.CharField(blank=True, default='13-03-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.CharField(blank=True, default='13-03-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='traineeattendance',
            name='date',
            field=models.CharField(blank=True, default='13-03-2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerattendance',
            name='date',
            field=models.CharField(blank=True, default='13-03-2021', max_length=100),
        ),
    ]
