# Generated by Django 3.1.5 on 2021-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210313_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='internattendance',
            name='half_day',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
