# Generated by Django 3.1.5 on 2021-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_internattendance_half_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internattendance',
            name='half_day',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
