# Generated by Django 3.1.5 on 2021-03-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210313_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internattendance',
            name='half_day',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='trainee_cource',
        ),
        migrations.AddField(
            model_name='trainee',
            name='traineecource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
