# Generated by Django 3.1.5 on 2021-03-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210313_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='intern_cource',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='internattendance',
            name='half_day',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='trainee_cource',
        ),
    ]
