# Generated by Django 3.1.5 on 2021-03-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210313_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='enddate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='startdate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='trainee_cource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
