# Generated by Django 3.1.5 on 2021-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210313_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='half_day',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='half_day',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='traineeattendance',
            name='half_day',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='trainerattendance',
            name='half_day',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
